// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.7
// source: grpc/cwm-rq-res-msg.proto

package grpcCWMPb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	cwmSIPPb "sol.go/cwm/proto/cwmSIPPb"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// -------------------FIRST SYNC MSG AFTER REGISTER ACC--------------------------------//
type InitialSyncMsgRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *InitialSyncMsgRequest) Reset() {
	*x = InitialSyncMsgRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_cwm_rq_res_msg_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InitialSyncMsgRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitialSyncMsgRequest) ProtoMessage() {}

func (x *InitialSyncMsgRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_cwm_rq_res_msg_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitialSyncMsgRequest.ProtoReflect.Descriptor instead.
func (*InitialSyncMsgRequest) Descriptor() ([]byte, []int) {
	return file_grpc_cwm_rq_res_msg_proto_rawDescGZIP(), []int{0}
}

type InitialSyncMsgResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GroupThreadInfo *GroupThreadInfo       `protobuf:"bytes,1,opt,name=groupThreadInfo,proto3" json:"groupThreadInfo,omitempty"`
	Msg             []*cwmSIPPb.CWMRequest `protobuf:"bytes,2,rep,name=msg,proto3" json:"msg,omitempty"`
}

func (x *InitialSyncMsgResponse) Reset() {
	*x = InitialSyncMsgResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_cwm_rq_res_msg_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InitialSyncMsgResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitialSyncMsgResponse) ProtoMessage() {}

func (x *InitialSyncMsgResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_cwm_rq_res_msg_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitialSyncMsgResponse.ProtoReflect.Descriptor instead.
func (*InitialSyncMsgResponse) Descriptor() ([]byte, []int) {
	return file_grpc_cwm_rq_res_msg_proto_rawDescGZIP(), []int{1}
}

func (x *InitialSyncMsgResponse) GetGroupThreadInfo() *GroupThreadInfo {
	if x != nil {
		return x.GroupThreadInfo
	}
	return nil
}

func (x *InitialSyncMsgResponse) GetMsg() []*cwmSIPPb.CWMRequest {
	if x != nil {
		return x.Msg
	}
	return nil
}

// -------------------SEND MSG--------------------------------//
type SendMsgRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Msg *cwmSIPPb.CWMRequest `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *SendMsgRequest) Reset() {
	*x = SendMsgRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_cwm_rq_res_msg_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendMsgRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMsgRequest) ProtoMessage() {}

func (x *SendMsgRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_cwm_rq_res_msg_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMsgRequest.ProtoReflect.Descriptor instead.
func (*SendMsgRequest) Descriptor() ([]byte, []int) {
	return file_grpc_cwm_rq_res_msg_proto_rawDescGZIP(), []int{2}
}

func (x *SendMsgRequest) GetMsg() *cwmSIPPb.CWMRequest {
	if x != nil {
		return x.Msg
	}
	return nil
}

type SendMsgResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MsgResponse *cwmSIPPb.CWMResponse `protobuf:"bytes,1,opt,name=msgResponse,proto3" json:"msgResponse,omitempty"`
}

func (x *SendMsgResponse) Reset() {
	*x = SendMsgResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_cwm_rq_res_msg_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendMsgResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMsgResponse) ProtoMessage() {}

func (x *SendMsgResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_cwm_rq_res_msg_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMsgResponse.ProtoReflect.Descriptor instead.
func (*SendMsgResponse) Descriptor() ([]byte, []int) {
	return file_grpc_cwm_rq_res_msg_proto_rawDescGZIP(), []int{3}
}

func (x *SendMsgResponse) GetMsgResponse() *cwmSIPPb.CWMResponse {
	if x != nil {
		return x.MsgResponse
	}
	return nil
}

// -------------------CONFIRM RECEIVED MSGs--------------------------------//
type ConfirmReceivedMsgsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MsgIds []string `protobuf:"bytes,1,rep,name=msgIds,proto3" json:"msgIds,omitempty"`
}

func (x *ConfirmReceivedMsgsRequest) Reset() {
	*x = ConfirmReceivedMsgsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_cwm_rq_res_msg_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConfirmReceivedMsgsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmReceivedMsgsRequest) ProtoMessage() {}

func (x *ConfirmReceivedMsgsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_cwm_rq_res_msg_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmReceivedMsgsRequest.ProtoReflect.Descriptor instead.
func (*ConfirmReceivedMsgsRequest) Descriptor() ([]byte, []int) {
	return file_grpc_cwm_rq_res_msg_proto_rawDescGZIP(), []int{4}
}

func (x *ConfirmReceivedMsgsRequest) GetMsgIds() []string {
	if x != nil {
		return x.MsgIds
	}
	return nil
}

type ConfirmReceivedMsgsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MsgIds []string `protobuf:"bytes,1,rep,name=msgIds,proto3" json:"msgIds,omitempty"`
}

func (x *ConfirmReceivedMsgsResponse) Reset() {
	*x = ConfirmReceivedMsgsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_cwm_rq_res_msg_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConfirmReceivedMsgsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmReceivedMsgsResponse) ProtoMessage() {}

func (x *ConfirmReceivedMsgsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_cwm_rq_res_msg_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmReceivedMsgsResponse.ProtoReflect.Descriptor instead.
func (*ConfirmReceivedMsgsResponse) Descriptor() ([]byte, []int) {
	return file_grpc_cwm_rq_res_msg_proto_rawDescGZIP(), []int{5}
}

func (x *ConfirmReceivedMsgsResponse) GetMsgIds() []string {
	if x != nil {
		return x.MsgIds
	}
	return nil
}

// -------------------GET ALL UNRECEIVE MSG--------------------------------//
type FetchAllUnreceivedMsgRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FromDate *int64 `protobuf:"varint,1,opt,name=fromDate,proto3,oneof" json:"fromDate,omitempty"`
	ToDate   *int64 `protobuf:"varint,2,opt,name=toDate,proto3,oneof" json:"toDate,omitempty"`
}

func (x *FetchAllUnreceivedMsgRequest) Reset() {
	*x = FetchAllUnreceivedMsgRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_cwm_rq_res_msg_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FetchAllUnreceivedMsgRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchAllUnreceivedMsgRequest) ProtoMessage() {}

func (x *FetchAllUnreceivedMsgRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_cwm_rq_res_msg_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchAllUnreceivedMsgRequest.ProtoReflect.Descriptor instead.
func (*FetchAllUnreceivedMsgRequest) Descriptor() ([]byte, []int) {
	return file_grpc_cwm_rq_res_msg_proto_rawDescGZIP(), []int{6}
}

func (x *FetchAllUnreceivedMsgRequest) GetFromDate() int64 {
	if x != nil && x.FromDate != nil {
		return *x.FromDate
	}
	return 0
}

func (x *FetchAllUnreceivedMsgRequest) GetToDate() int64 {
	if x != nil && x.ToDate != nil {
		return *x.ToDate
	}
	return 0
}

type FetchAllUnreceivedMsgResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Msg *cwmSIPPb.CWMRequest `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *FetchAllUnreceivedMsgResponse) Reset() {
	*x = FetchAllUnreceivedMsgResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_cwm_rq_res_msg_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FetchAllUnreceivedMsgResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchAllUnreceivedMsgResponse) ProtoMessage() {}

func (x *FetchAllUnreceivedMsgResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_cwm_rq_res_msg_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchAllUnreceivedMsgResponse.ProtoReflect.Descriptor instead.
func (*FetchAllUnreceivedMsgResponse) Descriptor() ([]byte, []int) {
	return file_grpc_cwm_rq_res_msg_proto_rawDescGZIP(), []int{7}
}

func (x *FetchAllUnreceivedMsgResponse) GetMsg() *cwmSIPPb.CWMRequest {
	if x != nil {
		return x.Msg
	}
	return nil
}

// -------------------GET OLD MSG OF THREAD--------------------------------//
type FetchOldMsgOfThreadRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ThreadId string `protobuf:"bytes,1,opt,name=threadId,proto3" json:"threadId,omitempty"`
	ToDate   int64  `protobuf:"varint,2,opt,name=toDate,proto3" json:"toDate,omitempty"`
	Limit    *int64 `protobuf:"varint,3,opt,name=limit,proto3,oneof" json:"limit,omitempty"`
}

func (x *FetchOldMsgOfThreadRequest) Reset() {
	*x = FetchOldMsgOfThreadRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_cwm_rq_res_msg_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FetchOldMsgOfThreadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchOldMsgOfThreadRequest) ProtoMessage() {}

func (x *FetchOldMsgOfThreadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_cwm_rq_res_msg_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchOldMsgOfThreadRequest.ProtoReflect.Descriptor instead.
func (*FetchOldMsgOfThreadRequest) Descriptor() ([]byte, []int) {
	return file_grpc_cwm_rq_res_msg_proto_rawDescGZIP(), []int{8}
}

func (x *FetchOldMsgOfThreadRequest) GetThreadId() string {
	if x != nil {
		return x.ThreadId
	}
	return ""
}

func (x *FetchOldMsgOfThreadRequest) GetToDate() int64 {
	if x != nil {
		return x.ToDate
	}
	return 0
}

func (x *FetchOldMsgOfThreadRequest) GetLimit() int64 {
	if x != nil && x.Limit != nil {
		return *x.Limit
	}
	return 0
}

type FetchOldMsgOfThreadResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Msg *cwmSIPPb.CWMRequest `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"` //CWMRequest
}

func (x *FetchOldMsgOfThreadResponse) Reset() {
	*x = FetchOldMsgOfThreadResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_cwm_rq_res_msg_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FetchOldMsgOfThreadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchOldMsgOfThreadResponse) ProtoMessage() {}

func (x *FetchOldMsgOfThreadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_cwm_rq_res_msg_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchOldMsgOfThreadResponse.ProtoReflect.Descriptor instead.
func (*FetchOldMsgOfThreadResponse) Descriptor() ([]byte, []int) {
	return file_grpc_cwm_rq_res_msg_proto_rawDescGZIP(), []int{9}
}

func (x *FetchOldMsgOfThreadResponse) GetMsg() *cwmSIPPb.CWMRequest {
	if x != nil {
		return x.Msg
	}
	return nil
}

// -------------------DELETE MSG--------------------------------//
type DeleteMsgsOfThreadRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ThreadId            string   `protobuf:"bytes,1,opt,name=threadId,proto3" json:"threadId,omitempty"`
	MsgIds              []string `protobuf:"bytes,2,rep,name=msgIds,proto3" json:"msgIds,omitempty"`
	DeleteForAllMembers bool     `protobuf:"varint,3,opt,name=deleteForAllMembers,proto3" json:"deleteForAllMembers,omitempty"`
}

func (x *DeleteMsgsOfThreadRequest) Reset() {
	*x = DeleteMsgsOfThreadRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_cwm_rq_res_msg_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteMsgsOfThreadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMsgsOfThreadRequest) ProtoMessage() {}

func (x *DeleteMsgsOfThreadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_cwm_rq_res_msg_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMsgsOfThreadRequest.ProtoReflect.Descriptor instead.
func (*DeleteMsgsOfThreadRequest) Descriptor() ([]byte, []int) {
	return file_grpc_cwm_rq_res_msg_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteMsgsOfThreadRequest) GetThreadId() string {
	if x != nil {
		return x.ThreadId
	}
	return ""
}

func (x *DeleteMsgsOfThreadRequest) GetMsgIds() []string {
	if x != nil {
		return x.MsgIds
	}
	return nil
}

func (x *DeleteMsgsOfThreadRequest) GetDeleteForAllMembers() bool {
	if x != nil {
		return x.DeleteForAllMembers
	}
	return false
}

type DeleteMsgsOfThreadResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Count int64 `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
}

func (x *DeleteMsgsOfThreadResponse) Reset() {
	*x = DeleteMsgsOfThreadResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_cwm_rq_res_msg_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteMsgsOfThreadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMsgsOfThreadResponse) ProtoMessage() {}

func (x *DeleteMsgsOfThreadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_cwm_rq_res_msg_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMsgsOfThreadResponse.ProtoReflect.Descriptor instead.
func (*DeleteMsgsOfThreadResponse) Descriptor() ([]byte, []int) {
	return file_grpc_cwm_rq_res_msg_proto_rawDescGZIP(), []int{11}
}

func (x *DeleteMsgsOfThreadResponse) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

// -------------------CLEAR ALL MSG OF THREAD--------------------------------//
type ClearAllMsgOfThreadRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ThreadId            string `protobuf:"bytes,1,opt,name=threadId,proto3" json:"threadId,omitempty"`
	DeleteForAllMembers bool   `protobuf:"varint,2,opt,name=deleteForAllMembers,proto3" json:"deleteForAllMembers,omitempty"`
}

func (x *ClearAllMsgOfThreadRequest) Reset() {
	*x = ClearAllMsgOfThreadRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_cwm_rq_res_msg_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClearAllMsgOfThreadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClearAllMsgOfThreadRequest) ProtoMessage() {}

func (x *ClearAllMsgOfThreadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_cwm_rq_res_msg_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClearAllMsgOfThreadRequest.ProtoReflect.Descriptor instead.
func (*ClearAllMsgOfThreadRequest) Descriptor() ([]byte, []int) {
	return file_grpc_cwm_rq_res_msg_proto_rawDescGZIP(), []int{12}
}

func (x *ClearAllMsgOfThreadRequest) GetThreadId() string {
	if x != nil {
		return x.ThreadId
	}
	return ""
}

func (x *ClearAllMsgOfThreadRequest) GetDeleteForAllMembers() bool {
	if x != nil {
		return x.DeleteForAllMembers
	}
	return false
}

type ClearAllMsgOfThreadResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Count int64 `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
}

func (x *ClearAllMsgOfThreadResponse) Reset() {
	*x = ClearAllMsgOfThreadResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_cwm_rq_res_msg_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClearAllMsgOfThreadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClearAllMsgOfThreadResponse) ProtoMessage() {}

func (x *ClearAllMsgOfThreadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_cwm_rq_res_msg_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClearAllMsgOfThreadResponse.ProtoReflect.Descriptor instead.
func (*ClearAllMsgOfThreadResponse) Descriptor() ([]byte, []int) {
	return file_grpc_cwm_rq_res_msg_proto_rawDescGZIP(), []int{13}
}

func (x *ClearAllMsgOfThreadResponse) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

// -------------------DELETE SOLO THREAD--------------------------------//
type DeleteSoloThreadRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ThreadId            string `protobuf:"bytes,1,opt,name=threadId,proto3" json:"threadId,omitempty"`
	DeleteForAllMembers bool   `protobuf:"varint,2,opt,name=deleteForAllMembers,proto3" json:"deleteForAllMembers,omitempty"`
}

func (x *DeleteSoloThreadRequest) Reset() {
	*x = DeleteSoloThreadRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_cwm_rq_res_msg_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteSoloThreadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSoloThreadRequest) ProtoMessage() {}

func (x *DeleteSoloThreadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_cwm_rq_res_msg_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSoloThreadRequest.ProtoReflect.Descriptor instead.
func (*DeleteSoloThreadRequest) Descriptor() ([]byte, []int) {
	return file_grpc_cwm_rq_res_msg_proto_rawDescGZIP(), []int{14}
}

func (x *DeleteSoloThreadRequest) GetThreadId() string {
	if x != nil {
		return x.ThreadId
	}
	return ""
}

func (x *DeleteSoloThreadRequest) GetDeleteForAllMembers() bool {
	if x != nil {
		return x.DeleteForAllMembers
	}
	return false
}

type DeleteSoloThreadResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Count int64 `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
}

func (x *DeleteSoloThreadResponse) Reset() {
	*x = DeleteSoloThreadResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_cwm_rq_res_msg_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteSoloThreadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSoloThreadResponse) ProtoMessage() {}

func (x *DeleteSoloThreadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_cwm_rq_res_msg_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSoloThreadResponse.ProtoReflect.Descriptor instead.
func (*DeleteSoloThreadResponse) Descriptor() ([]byte, []int) {
	return file_grpc_cwm_rq_res_msg_proto_rawDescGZIP(), []int{15}
}

func (x *DeleteSoloThreadResponse) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

// -------------------UPLOAD MEDIA MSG--------------------------------//
type UploadMediaMsgRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Data:
	//
	//	*UploadMediaMsgRequest_MediaMsgInfo
	//	*UploadMediaMsgRequest_ChunkData
	Data isUploadMediaMsgRequest_Data `protobuf_oneof:"data"`
}

func (x *UploadMediaMsgRequest) Reset() {
	*x = UploadMediaMsgRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_cwm_rq_res_msg_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UploadMediaMsgRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadMediaMsgRequest) ProtoMessage() {}

func (x *UploadMediaMsgRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_cwm_rq_res_msg_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadMediaMsgRequest.ProtoReflect.Descriptor instead.
func (*UploadMediaMsgRequest) Descriptor() ([]byte, []int) {
	return file_grpc_cwm_rq_res_msg_proto_rawDescGZIP(), []int{16}
}

func (m *UploadMediaMsgRequest) GetData() isUploadMediaMsgRequest_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

func (x *UploadMediaMsgRequest) GetMediaMsgInfo() *MediaMsgInfo {
	if x, ok := x.GetData().(*UploadMediaMsgRequest_MediaMsgInfo); ok {
		return x.MediaMsgInfo
	}
	return nil
}

func (x *UploadMediaMsgRequest) GetChunkData() []byte {
	if x, ok := x.GetData().(*UploadMediaMsgRequest_ChunkData); ok {
		return x.ChunkData
	}
	return nil
}

type isUploadMediaMsgRequest_Data interface {
	isUploadMediaMsgRequest_Data()
}

type UploadMediaMsgRequest_MediaMsgInfo struct {
	MediaMsgInfo *MediaMsgInfo `protobuf:"bytes,1,opt,name=mediaMsgInfo,proto3,oneof"`
}

type UploadMediaMsgRequest_ChunkData struct {
	ChunkData []byte `protobuf:"bytes,2,opt,name=chunk_data,json=chunkData,proto3,oneof"`
}

func (*UploadMediaMsgRequest_MediaMsgInfo) isUploadMediaMsgRequest_Data() {}

func (*UploadMediaMsgRequest_ChunkData) isUploadMediaMsgRequest_Data() {}

type UploadMediaMsgResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FileId   string `protobuf:"bytes,1,opt,name=fileId,proto3" json:"fileId,omitempty"`
	FileName string `protobuf:"bytes,2,opt,name=fileName,proto3" json:"fileName,omitempty"`
	FileSize int64  `protobuf:"varint,3,opt,name=fileSize,proto3" json:"fileSize,omitempty"`
	CheckSum string `protobuf:"bytes,4,opt,name=checkSum,proto3" json:"checkSum,omitempty"`
	MsgId    string `protobuf:"bytes,5,opt,name=msgId,proto3" json:"msgId,omitempty"`
}

func (x *UploadMediaMsgResponse) Reset() {
	*x = UploadMediaMsgResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_cwm_rq_res_msg_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UploadMediaMsgResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadMediaMsgResponse) ProtoMessage() {}

func (x *UploadMediaMsgResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_cwm_rq_res_msg_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadMediaMsgResponse.ProtoReflect.Descriptor instead.
func (*UploadMediaMsgResponse) Descriptor() ([]byte, []int) {
	return file_grpc_cwm_rq_res_msg_proto_rawDescGZIP(), []int{17}
}

func (x *UploadMediaMsgResponse) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

func (x *UploadMediaMsgResponse) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *UploadMediaMsgResponse) GetFileSize() int64 {
	if x != nil {
		return x.FileSize
	}
	return 0
}

func (x *UploadMediaMsgResponse) GetCheckSum() string {
	if x != nil {
		return x.CheckSum
	}
	return ""
}

func (x *UploadMediaMsgResponse) GetMsgId() string {
	if x != nil {
		return x.MsgId
	}
	return ""
}

// -------------------DOWNLOAD MEDIA FILE--------------------------------//
type DownloadMediaMsgRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FileId string `protobuf:"bytes,1,opt,name=fileId,proto3" json:"fileId,omitempty"`
	MsgId  string `protobuf:"bytes,2,opt,name=msgId,proto3" json:"msgId,omitempty"`
}

func (x *DownloadMediaMsgRequest) Reset() {
	*x = DownloadMediaMsgRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_cwm_rq_res_msg_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DownloadMediaMsgRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadMediaMsgRequest) ProtoMessage() {}

func (x *DownloadMediaMsgRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_cwm_rq_res_msg_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadMediaMsgRequest.ProtoReflect.Descriptor instead.
func (*DownloadMediaMsgRequest) Descriptor() ([]byte, []int) {
	return file_grpc_cwm_rq_res_msg_proto_rawDescGZIP(), []int{18}
}

func (x *DownloadMediaMsgRequest) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

func (x *DownloadMediaMsgRequest) GetMsgId() string {
	if x != nil {
		return x.MsgId
	}
	return ""
}

type DownloadMediaMsgResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ChunkData []byte `protobuf:"bytes,1,opt,name=chunk_data,json=chunkData,proto3" json:"chunk_data,omitempty"`
}

func (x *DownloadMediaMsgResponse) Reset() {
	*x = DownloadMediaMsgResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_cwm_rq_res_msg_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DownloadMediaMsgResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadMediaMsgResponse) ProtoMessage() {}

func (x *DownloadMediaMsgResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_cwm_rq_res_msg_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadMediaMsgResponse.ProtoReflect.Descriptor instead.
func (*DownloadMediaMsgResponse) Descriptor() ([]byte, []int) {
	return file_grpc_cwm_rq_res_msg_proto_rawDescGZIP(), []int{19}
}

func (x *DownloadMediaMsgResponse) GetChunkData() []byte {
	if x != nil {
		return x.ChunkData
	}
	return nil
}

var File_grpc_cwm_rq_res_msg_proto protoreflect.FileDescriptor

var file_grpc_cwm_rq_res_msg_proto_rawDesc = []byte{
	0x0a, 0x19, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x63, 0x77, 0x6d, 0x2d, 0x72, 0x71, 0x2d, 0x72, 0x65,
	0x73, 0x2d, 0x6d, 0x73, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x67, 0x72, 0x70,
	0x63, 0x43, 0x57, 0x4d, 0x50, 0x62, 0x1a, 0x14, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x63, 0x77, 0x6d,
	0x2d, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x10, 0x63, 0x77,
	0x6d, 0x2f, 0x63, 0x77, 0x6d, 0x53, 0x49, 0x50, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x17,
	0x0a, 0x15, 0x49, 0x6e, 0x69, 0x74, 0x69, 0x61, 0x6c, 0x53, 0x79, 0x6e, 0x63, 0x4d, 0x73, 0x67,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x86, 0x01, 0x0a, 0x16, 0x49, 0x6e, 0x69, 0x74,
	0x69, 0x61, 0x6c, 0x53, 0x79, 0x6e, 0x63, 0x4d, 0x73, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x44, 0x0a, 0x0f, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x54, 0x68, 0x72, 0x65, 0x61,
	0x64, 0x49, 0x6e, 0x66, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x72,
	0x70, 0x63, 0x43, 0x57, 0x4d, 0x50, 0x62, 0x2e, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x54, 0x68, 0x72,
	0x65, 0x61, 0x64, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x0f, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x54, 0x68,
	0x72, 0x65, 0x61, 0x64, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x26, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18,
	0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x63, 0x77, 0x6d, 0x53, 0x49, 0x50, 0x50, 0x62,
	0x2e, 0x43, 0x57, 0x4d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x03, 0x6d, 0x73, 0x67,
	0x22, 0x38, 0x0a, 0x0e, 0x53, 0x65, 0x6e, 0x64, 0x4d, 0x73, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x26, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x14, 0x2e, 0x63, 0x77, 0x6d, 0x53, 0x49, 0x50, 0x50, 0x62, 0x2e, 0x43, 0x57, 0x4d, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x22, 0x4a, 0x0a, 0x0f, 0x53, 0x65,
	0x6e, 0x64, 0x4d, 0x73, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x37, 0x0a,
	0x0b, 0x6d, 0x73, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x15, 0x2e, 0x63, 0x77, 0x6d, 0x53, 0x49, 0x50, 0x50, 0x62, 0x2e, 0x43, 0x57,
	0x4d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x0b, 0x6d, 0x73, 0x67, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x34, 0x0a, 0x1a, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x72,
	0x6d, 0x52, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x64, 0x4d, 0x73, 0x67, 0x73, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x6d, 0x73, 0x67, 0x49, 0x64, 0x73, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x09, 0x52, 0x06, 0x6d, 0x73, 0x67, 0x49, 0x64, 0x73, 0x22, 0x35, 0x0a, 0x1b,
	0x43, 0x6f, 0x6e, 0x66, 0x69, 0x72, 0x6d, 0x52, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x64, 0x4d,
	0x73, 0x67, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x6d,
	0x73, 0x67, 0x49, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x06, 0x6d, 0x73, 0x67,
	0x49, 0x64, 0x73, 0x22, 0x74, 0x0a, 0x1c, 0x46, 0x65, 0x74, 0x63, 0x68, 0x41, 0x6c, 0x6c, 0x55,
	0x6e, 0x72, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x64, 0x4d, 0x73, 0x67, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x1f, 0x0a, 0x08, 0x66, 0x72, 0x6f, 0x6d, 0x44, 0x61, 0x74, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x03, 0x48, 0x00, 0x52, 0x08, 0x66, 0x72, 0x6f, 0x6d, 0x44, 0x61, 0x74,
	0x65, 0x88, 0x01, 0x01, 0x12, 0x1b, 0x0a, 0x06, 0x74, 0x6f, 0x44, 0x61, 0x74, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x03, 0x48, 0x01, 0x52, 0x06, 0x74, 0x6f, 0x44, 0x61, 0x74, 0x65, 0x88, 0x01,
	0x01, 0x42, 0x0b, 0x0a, 0x09, 0x5f, 0x66, 0x72, 0x6f, 0x6d, 0x44, 0x61, 0x74, 0x65, 0x42, 0x09,
	0x0a, 0x07, 0x5f, 0x74, 0x6f, 0x44, 0x61, 0x74, 0x65, 0x22, 0x47, 0x0a, 0x1d, 0x46, 0x65, 0x74,
	0x63, 0x68, 0x41, 0x6c, 0x6c, 0x55, 0x6e, 0x72, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x64, 0x4d,
	0x73, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x26, 0x0a, 0x03, 0x6d, 0x73,
	0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x63, 0x77, 0x6d, 0x53, 0x49, 0x50,
	0x50, 0x62, 0x2e, 0x43, 0x57, 0x4d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x03, 0x6d,
	0x73, 0x67, 0x22, 0x75, 0x0a, 0x1a, 0x46, 0x65, 0x74, 0x63, 0x68, 0x4f, 0x6c, 0x64, 0x4d, 0x73,
	0x67, 0x4f, 0x66, 0x54, 0x68, 0x72, 0x65, 0x61, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x1a, 0x0a, 0x08, 0x74, 0x68, 0x72, 0x65, 0x61, 0x64, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x74, 0x68, 0x72, 0x65, 0x61, 0x64, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06,
	0x74, 0x6f, 0x44, 0x61, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x74, 0x6f,
	0x44, 0x61, 0x74, 0x65, 0x12, 0x19, 0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x03, 0x48, 0x00, 0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x88, 0x01, 0x01, 0x42,
	0x08, 0x0a, 0x06, 0x5f, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x22, 0x45, 0x0a, 0x1b, 0x46, 0x65, 0x74,
	0x63, 0x68, 0x4f, 0x6c, 0x64, 0x4d, 0x73, 0x67, 0x4f, 0x66, 0x54, 0x68, 0x72, 0x65, 0x61, 0x64,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x26, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x63, 0x77, 0x6d, 0x53, 0x49, 0x50, 0x50, 0x62,
	0x2e, 0x43, 0x57, 0x4d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x03, 0x6d, 0x73, 0x67,
	0x22, 0x81, 0x01, 0x0a, 0x19, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4d, 0x73, 0x67, 0x73, 0x4f,
	0x66, 0x54, 0x68, 0x72, 0x65, 0x61, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a,
	0x0a, 0x08, 0x74, 0x68, 0x72, 0x65, 0x61, 0x64, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x74, 0x68, 0x72, 0x65, 0x61, 0x64, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x6d, 0x73,
	0x67, 0x49, 0x64, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x06, 0x6d, 0x73, 0x67, 0x49,
	0x64, 0x73, 0x12, 0x30, 0x0a, 0x13, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x46, 0x6f, 0x72, 0x41,
	0x6c, 0x6c, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x13, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x46, 0x6f, 0x72, 0x41, 0x6c, 0x6c, 0x4d, 0x65, 0x6d,
	0x62, 0x65, 0x72, 0x73, 0x22, 0x32, 0x0a, 0x1a, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4d, 0x73,
	0x67, 0x73, 0x4f, 0x66, 0x54, 0x68, 0x72, 0x65, 0x61, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x6a, 0x0a, 0x1a, 0x43, 0x6c, 0x65, 0x61,
	0x72, 0x41, 0x6c, 0x6c, 0x4d, 0x73, 0x67, 0x4f, 0x66, 0x54, 0x68, 0x72, 0x65, 0x61, 0x64, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x74, 0x68, 0x72, 0x65, 0x61, 0x64,
	0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x74, 0x68, 0x72, 0x65, 0x61, 0x64,
	0x49, 0x64, 0x12, 0x30, 0x0a, 0x13, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x46, 0x6f, 0x72, 0x41,
	0x6c, 0x6c, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x13, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x46, 0x6f, 0x72, 0x41, 0x6c, 0x6c, 0x4d, 0x65, 0x6d,
	0x62, 0x65, 0x72, 0x73, 0x22, 0x33, 0x0a, 0x1b, 0x43, 0x6c, 0x65, 0x61, 0x72, 0x41, 0x6c, 0x6c,
	0x4d, 0x73, 0x67, 0x4f, 0x66, 0x54, 0x68, 0x72, 0x65, 0x61, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x67, 0x0a, 0x17, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x53, 0x6f, 0x6c, 0x6f, 0x54, 0x68, 0x72, 0x65, 0x61, 0x64, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x74, 0x68, 0x72, 0x65, 0x61, 0x64, 0x49, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x74, 0x68, 0x72, 0x65, 0x61, 0x64, 0x49, 0x64,
	0x12, 0x30, 0x0a, 0x13, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x46, 0x6f, 0x72, 0x41, 0x6c, 0x6c,
	0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x13, 0x64,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x46, 0x6f, 0x72, 0x41, 0x6c, 0x6c, 0x4d, 0x65, 0x6d, 0x62, 0x65,
	0x72, 0x73, 0x22, 0x30, 0x0a, 0x18, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x53, 0x6f, 0x6c, 0x6f,
	0x54, 0x68, 0x72, 0x65, 0x61, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14,
	0x0a, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x22, 0x7f, 0x0a, 0x15, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x4d, 0x65,
	0x64, 0x69, 0x61, 0x4d, 0x73, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x3d, 0x0a,
	0x0c, 0x6d, 0x65, 0x64, 0x69, 0x61, 0x4d, 0x73, 0x67, 0x49, 0x6e, 0x66, 0x6f, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x43, 0x57, 0x4d, 0x50, 0x62, 0x2e,
	0x4d, 0x65, 0x64, 0x69, 0x61, 0x4d, 0x73, 0x67, 0x49, 0x6e, 0x66, 0x6f, 0x48, 0x00, 0x52, 0x0c,
	0x6d, 0x65, 0x64, 0x69, 0x61, 0x4d, 0x73, 0x67, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x1f, 0x0a, 0x0a,
	0x63, 0x68, 0x75, 0x6e, 0x6b, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c,
	0x48, 0x00, 0x52, 0x09, 0x63, 0x68, 0x75, 0x6e, 0x6b, 0x44, 0x61, 0x74, 0x61, 0x42, 0x06, 0x0a,
	0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x9a, 0x01, 0x0a, 0x16, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64,
	0x4d, 0x65, 0x64, 0x69, 0x61, 0x4d, 0x73, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x16, 0x0a, 0x06, 0x66, 0x69, 0x6c, 0x65, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x66, 0x69, 0x6c, 0x65, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x66, 0x69, 0x6c, 0x65,
	0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x66, 0x69, 0x6c, 0x65,
	0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x53, 0x69, 0x7a, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x53, 0x69, 0x7a, 0x65,
	0x12, 0x1a, 0x0a, 0x08, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x53, 0x75, 0x6d, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x53, 0x75, 0x6d, 0x12, 0x14, 0x0a, 0x05,
	0x6d, 0x73, 0x67, 0x49, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6d, 0x73, 0x67,
	0x49, 0x64, 0x22, 0x47, 0x0a, 0x17, 0x44, 0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x4d, 0x65,
	0x64, 0x69, 0x61, 0x4d, 0x73, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a,
	0x06, 0x66, 0x69, 0x6c, 0x65, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x66,
	0x69, 0x6c, 0x65, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x6d, 0x73, 0x67, 0x49, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6d, 0x73, 0x67, 0x49, 0x64, 0x22, 0x39, 0x0a, 0x18, 0x44,
	0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x4d, 0x65, 0x64, 0x69, 0x61, 0x4d, 0x73, 0x67, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x68, 0x75, 0x6e, 0x6b,
	0x5f, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x63, 0x68, 0x75,
	0x6e, 0x6b, 0x44, 0x61, 0x74, 0x61, 0x42, 0x1c, 0x5a, 0x1a, 0x73, 0x6f, 0x6c, 0x2e, 0x67, 0x6f,
	0x2f, 0x63, 0x77, 0x6d, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x43,
	0x57, 0x4d, 0x50, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_grpc_cwm_rq_res_msg_proto_rawDescOnce sync.Once
	file_grpc_cwm_rq_res_msg_proto_rawDescData = file_grpc_cwm_rq_res_msg_proto_rawDesc
)

func file_grpc_cwm_rq_res_msg_proto_rawDescGZIP() []byte {
	file_grpc_cwm_rq_res_msg_proto_rawDescOnce.Do(func() {
		file_grpc_cwm_rq_res_msg_proto_rawDescData = protoimpl.X.CompressGZIP(file_grpc_cwm_rq_res_msg_proto_rawDescData)
	})
	return file_grpc_cwm_rq_res_msg_proto_rawDescData
}

var file_grpc_cwm_rq_res_msg_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_grpc_cwm_rq_res_msg_proto_goTypes = []interface{}{
	(*InitialSyncMsgRequest)(nil),         // 0: grpcCWMPb.InitialSyncMsgRequest
	(*InitialSyncMsgResponse)(nil),        // 1: grpcCWMPb.InitialSyncMsgResponse
	(*SendMsgRequest)(nil),                // 2: grpcCWMPb.SendMsgRequest
	(*SendMsgResponse)(nil),               // 3: grpcCWMPb.SendMsgResponse
	(*ConfirmReceivedMsgsRequest)(nil),    // 4: grpcCWMPb.ConfirmReceivedMsgsRequest
	(*ConfirmReceivedMsgsResponse)(nil),   // 5: grpcCWMPb.ConfirmReceivedMsgsResponse
	(*FetchAllUnreceivedMsgRequest)(nil),  // 6: grpcCWMPb.FetchAllUnreceivedMsgRequest
	(*FetchAllUnreceivedMsgResponse)(nil), // 7: grpcCWMPb.FetchAllUnreceivedMsgResponse
	(*FetchOldMsgOfThreadRequest)(nil),    // 8: grpcCWMPb.FetchOldMsgOfThreadRequest
	(*FetchOldMsgOfThreadResponse)(nil),   // 9: grpcCWMPb.FetchOldMsgOfThreadResponse
	(*DeleteMsgsOfThreadRequest)(nil),     // 10: grpcCWMPb.DeleteMsgsOfThreadRequest
	(*DeleteMsgsOfThreadResponse)(nil),    // 11: grpcCWMPb.DeleteMsgsOfThreadResponse
	(*ClearAllMsgOfThreadRequest)(nil),    // 12: grpcCWMPb.ClearAllMsgOfThreadRequest
	(*ClearAllMsgOfThreadResponse)(nil),   // 13: grpcCWMPb.ClearAllMsgOfThreadResponse
	(*DeleteSoloThreadRequest)(nil),       // 14: grpcCWMPb.DeleteSoloThreadRequest
	(*DeleteSoloThreadResponse)(nil),      // 15: grpcCWMPb.DeleteSoloThreadResponse
	(*UploadMediaMsgRequest)(nil),         // 16: grpcCWMPb.UploadMediaMsgRequest
	(*UploadMediaMsgResponse)(nil),        // 17: grpcCWMPb.UploadMediaMsgResponse
	(*DownloadMediaMsgRequest)(nil),       // 18: grpcCWMPb.DownloadMediaMsgRequest
	(*DownloadMediaMsgResponse)(nil),      // 19: grpcCWMPb.DownloadMediaMsgResponse
	(*GroupThreadInfo)(nil),               // 20: grpcCWMPb.GroupThreadInfo
	(*cwmSIPPb.CWMRequest)(nil),           // 21: cwmSIPPb.CWMRequest
	(*cwmSIPPb.CWMResponse)(nil),          // 22: cwmSIPPb.CWMResponse
	(*MediaMsgInfo)(nil),                  // 23: grpcCWMPb.MediaMsgInfo
}
var file_grpc_cwm_rq_res_msg_proto_depIdxs = []int32{
	20, // 0: grpcCWMPb.InitialSyncMsgResponse.groupThreadInfo:type_name -> grpcCWMPb.GroupThreadInfo
	21, // 1: grpcCWMPb.InitialSyncMsgResponse.msg:type_name -> cwmSIPPb.CWMRequest
	21, // 2: grpcCWMPb.SendMsgRequest.msg:type_name -> cwmSIPPb.CWMRequest
	22, // 3: grpcCWMPb.SendMsgResponse.msgResponse:type_name -> cwmSIPPb.CWMResponse
	21, // 4: grpcCWMPb.FetchAllUnreceivedMsgResponse.msg:type_name -> cwmSIPPb.CWMRequest
	21, // 5: grpcCWMPb.FetchOldMsgOfThreadResponse.msg:type_name -> cwmSIPPb.CWMRequest
	23, // 6: grpcCWMPb.UploadMediaMsgRequest.mediaMsgInfo:type_name -> grpcCWMPb.MediaMsgInfo
	7,  // [7:7] is the sub-list for method output_type
	7,  // [7:7] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_grpc_cwm_rq_res_msg_proto_init() }
func file_grpc_cwm_rq_res_msg_proto_init() {
	if File_grpc_cwm_rq_res_msg_proto != nil {
		return
	}
	file_grpc_cwm_model_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_grpc_cwm_rq_res_msg_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InitialSyncMsgRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_cwm_rq_res_msg_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InitialSyncMsgResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_cwm_rq_res_msg_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendMsgRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_cwm_rq_res_msg_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendMsgResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_cwm_rq_res_msg_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConfirmReceivedMsgsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_cwm_rq_res_msg_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConfirmReceivedMsgsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_cwm_rq_res_msg_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FetchAllUnreceivedMsgRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_cwm_rq_res_msg_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FetchAllUnreceivedMsgResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_cwm_rq_res_msg_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FetchOldMsgOfThreadRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_cwm_rq_res_msg_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FetchOldMsgOfThreadResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_cwm_rq_res_msg_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteMsgsOfThreadRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_cwm_rq_res_msg_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteMsgsOfThreadResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_cwm_rq_res_msg_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClearAllMsgOfThreadRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_cwm_rq_res_msg_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClearAllMsgOfThreadResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_cwm_rq_res_msg_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteSoloThreadRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_cwm_rq_res_msg_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteSoloThreadResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_cwm_rq_res_msg_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UploadMediaMsgRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_cwm_rq_res_msg_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UploadMediaMsgResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_cwm_rq_res_msg_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DownloadMediaMsgRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_cwm_rq_res_msg_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DownloadMediaMsgResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_grpc_cwm_rq_res_msg_proto_msgTypes[6].OneofWrappers = []interface{}{}
	file_grpc_cwm_rq_res_msg_proto_msgTypes[8].OneofWrappers = []interface{}{}
	file_grpc_cwm_rq_res_msg_proto_msgTypes[16].OneofWrappers = []interface{}{
		(*UploadMediaMsgRequest_MediaMsgInfo)(nil),
		(*UploadMediaMsgRequest_ChunkData)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_grpc_cwm_rq_res_msg_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_grpc_cwm_rq_res_msg_proto_goTypes,
		DependencyIndexes: file_grpc_cwm_rq_res_msg_proto_depIdxs,
		MessageInfos:      file_grpc_cwm_rq_res_msg_proto_msgTypes,
	}.Build()
	File_grpc_cwm_rq_res_msg_proto = out.File
	file_grpc_cwm_rq_res_msg_proto_rawDesc = nil
	file_grpc_cwm_rq_res_msg_proto_goTypes = nil
	file_grpc_cwm_rq_res_msg_proto_depIdxs = nil
}
