// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.7
// source: grpc/cwm-rq-res-account.proto

package grpcCWMPb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// -------------------CREATE ACCOUNT--------------------------------//
type CreatAccountRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Phone       string `protobuf:"bytes,1,opt,name=phone,proto3" json:"phone,omitempty"`
	CountryCode string `protobuf:"bytes,2,opt,name=countryCode,proto3" json:"countryCode,omitempty"`
}

func (x *CreatAccountRequest) Reset() {
	*x = CreatAccountRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_cwm_rq_res_account_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreatAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatAccountRequest) ProtoMessage() {}

func (x *CreatAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_cwm_rq_res_account_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatAccountRequest.ProtoReflect.Descriptor instead.
func (*CreatAccountRequest) Descriptor() ([]byte, []int) {
	return file_grpc_cwm_rq_res_account_proto_rawDescGZIP(), []int{0}
}

func (x *CreatAccountRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *CreatAccountRequest) GetCountryCode() string {
	if x != nil {
		return x.CountryCode
	}
	return ""
}

type CreatAccountResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PhoneFull         string `protobuf:"bytes,1,opt,name=phoneFull,proto3" json:"phoneFull,omitempty"`
	AuthenCodeTimeOut int32  `protobuf:"varint,2,opt,name=authenCodeTimeOut,proto3" json:"authenCodeTimeOut,omitempty"`
	NumberPrefix      string `protobuf:"bytes,3,opt,name=numberPrefix,proto3" json:"numberPrefix,omitempty"`
}

func (x *CreatAccountResponse) Reset() {
	*x = CreatAccountResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_cwm_rq_res_account_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreatAccountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatAccountResponse) ProtoMessage() {}

func (x *CreatAccountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_cwm_rq_res_account_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatAccountResponse.ProtoReflect.Descriptor instead.
func (*CreatAccountResponse) Descriptor() ([]byte, []int) {
	return file_grpc_cwm_rq_res_account_proto_rawDescGZIP(), []int{1}
}

func (x *CreatAccountResponse) GetPhoneFull() string {
	if x != nil {
		return x.PhoneFull
	}
	return ""
}

func (x *CreatAccountResponse) GetAuthenCodeTimeOut() int32 {
	if x != nil {
		return x.AuthenCodeTimeOut
	}
	return 0
}

func (x *CreatAccountResponse) GetNumberPrefix() string {
	if x != nil {
		return x.NumberPrefix
	}
	return ""
}

type VerifyAuthencodeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Phone       string      `protobuf:"bytes,1,opt,name=phone,proto3" json:"phone,omitempty"`
	CountryCode string      `protobuf:"bytes,2,opt,name=countryCode,proto3" json:"countryCode,omitempty"`
	DeviceInfo  *DeviceInfo `protobuf:"bytes,3,opt,name=deviceInfo,proto3" json:"deviceInfo,omitempty"`
	Authencode  string      `protobuf:"bytes,4,opt,name=authencode,proto3" json:"authencode,omitempty"`
}

func (x *VerifyAuthencodeRequest) Reset() {
	*x = VerifyAuthencodeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_cwm_rq_res_account_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VerifyAuthencodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyAuthencodeRequest) ProtoMessage() {}

func (x *VerifyAuthencodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_cwm_rq_res_account_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyAuthencodeRequest.ProtoReflect.Descriptor instead.
func (*VerifyAuthencodeRequest) Descriptor() ([]byte, []int) {
	return file_grpc_cwm_rq_res_account_proto_rawDescGZIP(), []int{2}
}

func (x *VerifyAuthencodeRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *VerifyAuthencodeRequest) GetCountryCode() string {
	if x != nil {
		return x.CountryCode
	}
	return ""
}

func (x *VerifyAuthencodeRequest) GetDeviceInfo() *DeviceInfo {
	if x != nil {
		return x.DeviceInfo
	}
	return nil
}

func (x *VerifyAuthencodeRequest) GetAuthencode() string {
	if x != nil {
		return x.Authencode
	}
	return ""
}

type VerifyAuthencodeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PassEnc    []byte      `protobuf:"bytes,1,opt,name=passEnc,proto3" json:"passEnc,omitempty"`
	Iv         []byte      `protobuf:"bytes,2,opt,name=iv,proto3" json:"iv,omitempty"`
	DeviceInfo *DeviceInfo `protobuf:"bytes,3,opt,name=deviceInfo,proto3" json:"deviceInfo,omitempty"`
	Nonce      string      `protobuf:"bytes,4,opt,name=nonce,proto3" json:"nonce,omitempty"`
	FirstName  string      `protobuf:"bytes,5,opt,name=firstName,proto3" json:"firstName,omitempty"`
	LastName   string      `protobuf:"bytes,6,opt,name=lastName,proto3" json:"lastName,omitempty"`
	UserName   string      `protobuf:"bytes,7,opt,name=userName,proto3" json:"userName,omitempty"`
}

func (x *VerifyAuthencodeResponse) Reset() {
	*x = VerifyAuthencodeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_cwm_rq_res_account_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VerifyAuthencodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyAuthencodeResponse) ProtoMessage() {}

func (x *VerifyAuthencodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_cwm_rq_res_account_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyAuthencodeResponse.ProtoReflect.Descriptor instead.
func (*VerifyAuthencodeResponse) Descriptor() ([]byte, []int) {
	return file_grpc_cwm_rq_res_account_proto_rawDescGZIP(), []int{3}
}

func (x *VerifyAuthencodeResponse) GetPassEnc() []byte {
	if x != nil {
		return x.PassEnc
	}
	return nil
}

func (x *VerifyAuthencodeResponse) GetIv() []byte {
	if x != nil {
		return x.Iv
	}
	return nil
}

func (x *VerifyAuthencodeResponse) GetDeviceInfo() *DeviceInfo {
	if x != nil {
		return x.DeviceInfo
	}
	return nil
}

func (x *VerifyAuthencodeResponse) GetNonce() string {
	if x != nil {
		return x.Nonce
	}
	return ""
}

func (x *VerifyAuthencodeResponse) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *VerifyAuthencodeResponse) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *VerifyAuthencodeResponse) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

type LoginRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PhoneFull string `protobuf:"bytes,1,opt,name=phoneFull,proto3" json:"phoneFull,omitempty"`
	SessionId string `protobuf:"bytes,2,opt,name=sessionId,proto3" json:"sessionId,omitempty"`
	Nonce     string `protobuf:"bytes,3,opt,name=nonce,proto3" json:"nonce,omitempty"`
	Response  string `protobuf:"bytes,4,opt,name=response,proto3" json:"response,omitempty"`
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_cwm_rq_res_account_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_cwm_rq_res_account_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_grpc_cwm_rq_res_account_proto_rawDescGZIP(), []int{4}
}

func (x *LoginRequest) GetPhoneFull() string {
	if x != nil {
		return x.PhoneFull
	}
	return ""
}

func (x *LoginRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *LoginRequest) GetNonce() string {
	if x != nil {
		return x.Nonce
	}
	return ""
}

func (x *LoginRequest) GetResponse() string {
	if x != nil {
		return x.Response
	}
	return ""
}

type LoginResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Jwt    string `protobuf:"bytes,1,opt,name=jwt,proto3" json:"jwt,omitempty"`
	JwtTTL int32  `protobuf:"varint,2,opt,name=jwtTTL,proto3" json:"jwtTTL,omitempty"` //minutes
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_cwm_rq_res_account_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse) ProtoMessage() {}

func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_cwm_rq_res_account_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponse.ProtoReflect.Descriptor instead.
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return file_grpc_cwm_rq_res_account_proto_rawDescGZIP(), []int{5}
}

func (x *LoginResponse) GetJwt() string {
	if x != nil {
		return x.Jwt
	}
	return ""
}

func (x *LoginResponse) GetJwtTTL() int32 {
	if x != nil {
		return x.JwtTTL
	}
	return 0
}

type SyncContactRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ContactInfo *ContactInfo `protobuf:"bytes,3,opt,name=contactInfo,proto3" json:"contactInfo,omitempty"`
}

func (x *SyncContactRequest) Reset() {
	*x = SyncContactRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_cwm_rq_res_account_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SyncContactRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncContactRequest) ProtoMessage() {}

func (x *SyncContactRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_cwm_rq_res_account_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncContactRequest.ProtoReflect.Descriptor instead.
func (*SyncContactRequest) Descriptor() ([]byte, []int) {
	return file_grpc_cwm_rq_res_account_proto_rawDescGZIP(), []int{6}
}

func (x *SyncContactRequest) GetContactInfo() *ContactInfo {
	if x != nil {
		return x.ContactInfo
	}
	return nil
}

type SyncContactResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ContactInfo *ContactInfo `protobuf:"bytes,3,opt,name=contactInfo,proto3" json:"contactInfo,omitempty"`
}

func (x *SyncContactResponse) Reset() {
	*x = SyncContactResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_cwm_rq_res_account_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SyncContactResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncContactResponse) ProtoMessage() {}

func (x *SyncContactResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_cwm_rq_res_account_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncContactResponse.ProtoReflect.Descriptor instead.
func (*SyncContactResponse) Descriptor() ([]byte, []int) {
	return file_grpc_cwm_rq_res_account_proto_rawDescGZIP(), []int{7}
}

func (x *SyncContactResponse) GetContactInfo() *ContactInfo {
	if x != nil {
		return x.ContactInfo
	}
	return nil
}

// -------------------UPDATE PROFILE--------------------------------//
type UpdateProfileRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FirstName string `protobuf:"bytes,1,opt,name=firstName,proto3" json:"firstName,omitempty"`
	LastName  string `protobuf:"bytes,2,opt,name=lastName,proto3" json:"lastName,omitempty"`
}

func (x *UpdateProfileRequest) Reset() {
	*x = UpdateProfileRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_cwm_rq_res_account_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProfileRequest) ProtoMessage() {}

func (x *UpdateProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_cwm_rq_res_account_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProfileRequest.ProtoReflect.Descriptor instead.
func (*UpdateProfileRequest) Descriptor() ([]byte, []int) {
	return file_grpc_cwm_rq_res_account_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateProfileRequest) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *UpdateProfileRequest) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

type UpdateProfileResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FirstName string `protobuf:"bytes,1,opt,name=firstName,proto3" json:"firstName,omitempty"`
	LastName  string `protobuf:"bytes,2,opt,name=lastName,proto3" json:"lastName,omitempty"`
}

func (x *UpdateProfileResponse) Reset() {
	*x = UpdateProfileResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_cwm_rq_res_account_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProfileResponse) ProtoMessage() {}

func (x *UpdateProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_cwm_rq_res_account_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProfileResponse.ProtoReflect.Descriptor instead.
func (*UpdateProfileResponse) Descriptor() ([]byte, []int) {
	return file_grpc_cwm_rq_res_account_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateProfileResponse) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *UpdateProfileResponse) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

// -------------------UPDATE USERNAME--------------------------------//
type UpdateUsernameRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserName string `protobuf:"bytes,1,opt,name=userName,proto3" json:"userName,omitempty"`
}

func (x *UpdateUsernameRequest) Reset() {
	*x = UpdateUsernameRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_cwm_rq_res_account_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateUsernameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUsernameRequest) ProtoMessage() {}

func (x *UpdateUsernameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_cwm_rq_res_account_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUsernameRequest.ProtoReflect.Descriptor instead.
func (*UpdateUsernameRequest) Descriptor() ([]byte, []int) {
	return file_grpc_cwm_rq_res_account_proto_rawDescGZIP(), []int{10}
}

func (x *UpdateUsernameRequest) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

type UpdateUsernameResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserName string `protobuf:"bytes,1,opt,name=userName,proto3" json:"userName,omitempty"`
}

func (x *UpdateUsernameResponse) Reset() {
	*x = UpdateUsernameResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_cwm_rq_res_account_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateUsernameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUsernameResponse) ProtoMessage() {}

func (x *UpdateUsernameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_cwm_rq_res_account_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUsernameResponse.ProtoReflect.Descriptor instead.
func (*UpdateUsernameResponse) Descriptor() ([]byte, []int) {
	return file_grpc_cwm_rq_res_account_proto_rawDescGZIP(), []int{11}
}

func (x *UpdateUsernameResponse) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

// -------------------SEARCH BY USERNAME--------------------------------//
type SearchByUsernameRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserName string `protobuf:"bytes,1,opt,name=userName,proto3" json:"userName,omitempty"`
}

func (x *SearchByUsernameRequest) Reset() {
	*x = SearchByUsernameRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_cwm_rq_res_account_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearchByUsernameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchByUsernameRequest) ProtoMessage() {}

func (x *SearchByUsernameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_cwm_rq_res_account_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchByUsernameRequest.ProtoReflect.Descriptor instead.
func (*SearchByUsernameRequest) Descriptor() ([]byte, []int) {
	return file_grpc_cwm_rq_res_account_proto_rawDescGZIP(), []int{12}
}

func (x *SearchByUsernameRequest) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

type SearchByUsernameResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SearchUserInfos []*SearchUserInfo `protobuf:"bytes,1,rep,name=searchUserInfos,proto3" json:"searchUserInfos,omitempty"`
}

func (x *SearchByUsernameResponse) Reset() {
	*x = SearchByUsernameResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_cwm_rq_res_account_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearchByUsernameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchByUsernameResponse) ProtoMessage() {}

func (x *SearchByUsernameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_cwm_rq_res_account_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchByUsernameResponse.ProtoReflect.Descriptor instead.
func (*SearchByUsernameResponse) Descriptor() ([]byte, []int) {
	return file_grpc_cwm_rq_res_account_proto_rawDescGZIP(), []int{13}
}

func (x *SearchByUsernameResponse) GetSearchUserInfos() []*SearchUserInfo {
	if x != nil {
		return x.SearchUserInfos
	}
	return nil
}

// -------------------SEARCH BY PHONEFULL--------------------------------//
type SearchByPhoneFullRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PhoneFull string `protobuf:"bytes,1,opt,name=phoneFull,proto3" json:"phoneFull,omitempty"`
}

func (x *SearchByPhoneFullRequest) Reset() {
	*x = SearchByPhoneFullRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_cwm_rq_res_account_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearchByPhoneFullRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchByPhoneFullRequest) ProtoMessage() {}

func (x *SearchByPhoneFullRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_cwm_rq_res_account_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchByPhoneFullRequest.ProtoReflect.Descriptor instead.
func (*SearchByPhoneFullRequest) Descriptor() ([]byte, []int) {
	return file_grpc_cwm_rq_res_account_proto_rawDescGZIP(), []int{14}
}

func (x *SearchByPhoneFullRequest) GetPhoneFull() string {
	if x != nil {
		return x.PhoneFull
	}
	return ""
}

type SearchByPhoneFullResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SearchUserInfos []*SearchUserInfo `protobuf:"bytes,1,rep,name=searchUserInfos,proto3" json:"searchUserInfos,omitempty"`
}

func (x *SearchByPhoneFullResponse) Reset() {
	*x = SearchByPhoneFullResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_cwm_rq_res_account_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearchByPhoneFullResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchByPhoneFullResponse) ProtoMessage() {}

func (x *SearchByPhoneFullResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_cwm_rq_res_account_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchByPhoneFullResponse.ProtoReflect.Descriptor instead.
func (*SearchByPhoneFullResponse) Descriptor() ([]byte, []int) {
	return file_grpc_cwm_rq_res_account_proto_rawDescGZIP(), []int{15}
}

func (x *SearchByPhoneFullResponse) GetSearchUserInfos() []*SearchUserInfo {
	if x != nil {
		return x.SearchUserInfos
	}
	return nil
}

// -------------------SEARCH BY PHONEFULL--------------------------------//
type FindByListPhoneFullRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PhoneFulls []string `protobuf:"bytes,1,rep,name=phoneFulls,proto3" json:"phoneFulls,omitempty"`
}

func (x *FindByListPhoneFullRequest) Reset() {
	*x = FindByListPhoneFullRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_cwm_rq_res_account_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FindByListPhoneFullRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindByListPhoneFullRequest) ProtoMessage() {}

func (x *FindByListPhoneFullRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_cwm_rq_res_account_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindByListPhoneFullRequest.ProtoReflect.Descriptor instead.
func (*FindByListPhoneFullRequest) Descriptor() ([]byte, []int) {
	return file_grpc_cwm_rq_res_account_proto_rawDescGZIP(), []int{16}
}

func (x *FindByListPhoneFullRequest) GetPhoneFulls() []string {
	if x != nil {
		return x.PhoneFulls
	}
	return nil
}

type FindByListPhoneFullResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SearchUserInfos []*SearchUserInfo `protobuf:"bytes,1,rep,name=searchUserInfos,proto3" json:"searchUserInfos,omitempty"`
}

func (x *FindByListPhoneFullResponse) Reset() {
	*x = FindByListPhoneFullResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_cwm_rq_res_account_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FindByListPhoneFullResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindByListPhoneFullResponse) ProtoMessage() {}

func (x *FindByListPhoneFullResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_cwm_rq_res_account_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindByListPhoneFullResponse.ProtoReflect.Descriptor instead.
func (*FindByListPhoneFullResponse) Descriptor() ([]byte, []int) {
	return file_grpc_cwm_rq_res_account_proto_rawDescGZIP(), []int{17}
}

func (x *FindByListPhoneFullResponse) GetSearchUserInfos() []*SearchUserInfo {
	if x != nil {
		return x.SearchUserInfos
	}
	return nil
}

// -------------------UPDATE PUSH TOKEN--------------------------------//
type UpdatePushTokenRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PushTokenInfo *PushTokenInfo `protobuf:"bytes,1,opt,name=pushTokenInfo,proto3" json:"pushTokenInfo,omitempty"`
}

func (x *UpdatePushTokenRequest) Reset() {
	*x = UpdatePushTokenRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_cwm_rq_res_account_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdatePushTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePushTokenRequest) ProtoMessage() {}

func (x *UpdatePushTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_cwm_rq_res_account_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePushTokenRequest.ProtoReflect.Descriptor instead.
func (*UpdatePushTokenRequest) Descriptor() ([]byte, []int) {
	return file_grpc_cwm_rq_res_account_proto_rawDescGZIP(), []int{18}
}

func (x *UpdatePushTokenRequest) GetPushTokenInfo() *PushTokenInfo {
	if x != nil {
		return x.PushTokenInfo
	}
	return nil
}

type UpdatePushTokenResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PushTokenInfo *PushTokenInfo `protobuf:"bytes,1,opt,name=pushTokenInfo,proto3" json:"pushTokenInfo,omitempty"`
}

func (x *UpdatePushTokenResponse) Reset() {
	*x = UpdatePushTokenResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_cwm_rq_res_account_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdatePushTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePushTokenResponse) ProtoMessage() {}

func (x *UpdatePushTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_cwm_rq_res_account_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePushTokenResponse.ProtoReflect.Descriptor instead.
func (*UpdatePushTokenResponse) Descriptor() ([]byte, []int) {
	return file_grpc_cwm_rq_res_account_proto_rawDescGZIP(), []int{19}
}

func (x *UpdatePushTokenResponse) GetPushTokenInfo() *PushTokenInfo {
	if x != nil {
		return x.PushTokenInfo
	}
	return nil
}

var File_grpc_cwm_rq_res_account_proto protoreflect.FileDescriptor

var file_grpc_cwm_rq_res_account_proto_rawDesc = []byte{
	0x0a, 0x1d, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x63, 0x77, 0x6d, 0x2d, 0x72, 0x71, 0x2d, 0x72, 0x65,
	0x73, 0x2d, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x09, 0x67, 0x72, 0x70, 0x63, 0x43, 0x57, 0x4d, 0x50, 0x62, 0x1a, 0x14, 0x67, 0x72, 0x70, 0x63,
	0x2f, 0x63, 0x77, 0x6d, 0x2d, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0x4d, 0x0a, 0x13, 0x43, 0x72, 0x65, 0x61, 0x74, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x68, 0x6f, 0x6e, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x12, 0x20, 0x0a,
	0x0b, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0b, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79, 0x43, 0x6f, 0x64, 0x65, 0x22,
	0x86, 0x01, 0x0a, 0x14, 0x43, 0x72, 0x65, 0x61, 0x74, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x70, 0x68, 0x6f, 0x6e,
	0x65, 0x46, 0x75, 0x6c, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x70, 0x68, 0x6f,
	0x6e, 0x65, 0x46, 0x75, 0x6c, 0x6c, 0x12, 0x2c, 0x0a, 0x11, 0x61, 0x75, 0x74, 0x68, 0x65, 0x6e,
	0x43, 0x6f, 0x64, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x4f, 0x75, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x11, 0x61, 0x75, 0x74, 0x68, 0x65, 0x6e, 0x43, 0x6f, 0x64, 0x65, 0x54, 0x69, 0x6d,
	0x65, 0x4f, 0x75, 0x74, 0x12, 0x22, 0x0a, 0x0c, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x50, 0x72,
	0x65, 0x66, 0x69, 0x78, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x6e, 0x75, 0x6d, 0x62,
	0x65, 0x72, 0x50, 0x72, 0x65, 0x66, 0x69, 0x78, 0x22, 0xa8, 0x01, 0x0a, 0x17, 0x56, 0x65, 0x72,
	0x69, 0x66, 0x79, 0x41, 0x75, 0x74, 0x68, 0x65, 0x6e, 0x63, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x72, 0x79, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0b, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x35, 0x0a, 0x0a,
	0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x15, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x43, 0x57, 0x4d, 0x50, 0x62, 0x2e, 0x44, 0x65, 0x76,
	0x69, 0x63, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x0a, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x49,
	0x6e, 0x66, 0x6f, 0x12, 0x1e, 0x0a, 0x0a, 0x61, 0x75, 0x74, 0x68, 0x65, 0x6e, 0x63, 0x6f, 0x64,
	0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x61, 0x75, 0x74, 0x68, 0x65, 0x6e, 0x63,
	0x6f, 0x64, 0x65, 0x22, 0xe7, 0x01, 0x0a, 0x18, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x41, 0x75,
	0x74, 0x68, 0x65, 0x6e, 0x63, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x18, 0x0a, 0x07, 0x70, 0x61, 0x73, 0x73, 0x45, 0x6e, 0x63, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x07, 0x70, 0x61, 0x73, 0x73, 0x45, 0x6e, 0x63, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x76,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x02, 0x69, 0x76, 0x12, 0x35, 0x0a, 0x0a, 0x64, 0x65,
	0x76, 0x69, 0x63, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15,
	0x2e, 0x67, 0x72, 0x70, 0x63, 0x43, 0x57, 0x4d, 0x50, 0x62, 0x2e, 0x44, 0x65, 0x76, 0x69, 0x63,
	0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x0a, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x49, 0x6e, 0x66,
	0x6f, 0x12, 0x14, 0x0a, 0x05, 0x6e, 0x6f, 0x6e, 0x63, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x6e, 0x6f, 0x6e, 0x63, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x66, 0x69, 0x72, 0x73, 0x74,
	0x4e, 0x61, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x66, 0x69, 0x72, 0x73,
	0x74, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x6c, 0x61, 0x73, 0x74, 0x4e, 0x61, 0x6d,
	0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6c, 0x61, 0x73, 0x74, 0x4e, 0x61, 0x6d,
	0x65, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x07, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x7c, 0x0a,
	0x0c, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1c, 0x0a,
	0x09, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x46, 0x75, 0x6c, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x09, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x46, 0x75, 0x6c, 0x6c, 0x12, 0x1c, 0x0a, 0x09, 0x73,
	0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09,
	0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x6e, 0x6f, 0x6e,
	0x63, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6e, 0x6f, 0x6e, 0x63, 0x65, 0x12,
	0x1a, 0x0a, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x39, 0x0a, 0x0d, 0x4c,
	0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x10, 0x0a, 0x03,
	0x6a, 0x77, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6a, 0x77, 0x74, 0x12, 0x16,
	0x0a, 0x06, 0x6a, 0x77, 0x74, 0x54, 0x54, 0x4c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06,
	0x6a, 0x77, 0x74, 0x54, 0x54, 0x4c, 0x22, 0x4e, 0x0a, 0x12, 0x53, 0x79, 0x6e, 0x63, 0x43, 0x6f,
	0x6e, 0x74, 0x61, 0x63, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x38, 0x0a, 0x0b,
	0x63, 0x6f, 0x6e, 0x74, 0x61, 0x63, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x16, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x43, 0x57, 0x4d, 0x50, 0x62, 0x2e, 0x43, 0x6f,
	0x6e, 0x74, 0x61, 0x63, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x0b, 0x63, 0x6f, 0x6e, 0x74, 0x61,
	0x63, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x22, 0x4f, 0x0a, 0x13, 0x53, 0x79, 0x6e, 0x63, 0x43, 0x6f,
	0x6e, 0x74, 0x61, 0x63, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x38, 0x0a,
	0x0b, 0x63, 0x6f, 0x6e, 0x74, 0x61, 0x63, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x16, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x43, 0x57, 0x4d, 0x50, 0x62, 0x2e, 0x43,
	0x6f, 0x6e, 0x74, 0x61, 0x63, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x0b, 0x63, 0x6f, 0x6e, 0x74,
	0x61, 0x63, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x22, 0x50, 0x0a, 0x14, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x1c, 0x0a, 0x09, 0x66, 0x69, 0x72, 0x73, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x09, 0x66, 0x69, 0x72, 0x73, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a,
	0x08, 0x6c, 0x61, 0x73, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x6c, 0x61, 0x73, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x51, 0x0a, 0x15, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x66, 0x69, 0x72, 0x73, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x66, 0x69, 0x72, 0x73, 0x74, 0x4e, 0x61, 0x6d, 0x65,
	0x12, 0x1a, 0x0a, 0x08, 0x6c, 0x61, 0x73, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x6c, 0x61, 0x73, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x33, 0x0a, 0x15,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x55, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x4e, 0x61, 0x6d,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x4e, 0x61, 0x6d,
	0x65, 0x22, 0x34, 0x0a, 0x16, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x55, 0x73, 0x65, 0x72, 0x6e,
	0x61, 0x6d, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x75,
	0x73, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75,
	0x73, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x35, 0x0a, 0x17, 0x53, 0x65, 0x61, 0x72, 0x63,
	0x68, 0x42, 0x79, 0x55, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x5f,
	0x0a, 0x18, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x42, 0x79, 0x55, 0x73, 0x65, 0x72, 0x6e, 0x61,
	0x6d, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x43, 0x0a, 0x0f, 0x73, 0x65,
	0x61, 0x72, 0x63, 0x68, 0x55, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x43, 0x57, 0x4d, 0x50, 0x62, 0x2e,
	0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x55, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x0f,
	0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x55, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x73, 0x22,
	0x38, 0x0a, 0x18, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x42, 0x79, 0x50, 0x68, 0x6f, 0x6e, 0x65,
	0x46, 0x75, 0x6c, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x70,
	0x68, 0x6f, 0x6e, 0x65, 0x46, 0x75, 0x6c, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09,
	0x70, 0x68, 0x6f, 0x6e, 0x65, 0x46, 0x75, 0x6c, 0x6c, 0x22, 0x60, 0x0a, 0x19, 0x53, 0x65, 0x61,
	0x72, 0x63, 0x68, 0x42, 0x79, 0x50, 0x68, 0x6f, 0x6e, 0x65, 0x46, 0x75, 0x6c, 0x6c, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x43, 0x0a, 0x0f, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68,
	0x55, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x19, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x43, 0x57, 0x4d, 0x50, 0x62, 0x2e, 0x53, 0x65, 0x61, 0x72,
	0x63, 0x68, 0x55, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x0f, 0x73, 0x65, 0x61, 0x72,
	0x63, 0x68, 0x55, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x73, 0x22, 0x3c, 0x0a, 0x1a, 0x46,
	0x69, 0x6e, 0x64, 0x42, 0x79, 0x4c, 0x69, 0x73, 0x74, 0x50, 0x68, 0x6f, 0x6e, 0x65, 0x46, 0x75,
	0x6c, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x70, 0x68, 0x6f,
	0x6e, 0x65, 0x46, 0x75, 0x6c, 0x6c, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0a, 0x70,
	0x68, 0x6f, 0x6e, 0x65, 0x46, 0x75, 0x6c, 0x6c, 0x73, 0x22, 0x62, 0x0a, 0x1b, 0x46, 0x69, 0x6e,
	0x64, 0x42, 0x79, 0x4c, 0x69, 0x73, 0x74, 0x50, 0x68, 0x6f, 0x6e, 0x65, 0x46, 0x75, 0x6c, 0x6c,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x43, 0x0a, 0x0f, 0x73, 0x65, 0x61, 0x72,
	0x63, 0x68, 0x55, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x19, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x43, 0x57, 0x4d, 0x50, 0x62, 0x2e, 0x53, 0x65,
	0x61, 0x72, 0x63, 0x68, 0x55, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x0f, 0x73, 0x65,
	0x61, 0x72, 0x63, 0x68, 0x55, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x73, 0x22, 0x58, 0x0a,
	0x16, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x50, 0x75, 0x73, 0x68, 0x54, 0x6f, 0x6b, 0x65, 0x6e,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x3e, 0x0a, 0x0d, 0x70, 0x75, 0x73, 0x68, 0x54,
	0x6f, 0x6b, 0x65, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18,
	0x2e, 0x67, 0x72, 0x70, 0x63, 0x43, 0x57, 0x4d, 0x50, 0x62, 0x2e, 0x50, 0x75, 0x73, 0x68, 0x54,
	0x6f, 0x6b, 0x65, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x0d, 0x70, 0x75, 0x73, 0x68, 0x54, 0x6f,
	0x6b, 0x65, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x22, 0x59, 0x0a, 0x17, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x50, 0x75, 0x73, 0x68, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x3e, 0x0a, 0x0d, 0x70, 0x75, 0x73, 0x68, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x49,
	0x6e, 0x66, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x67, 0x72, 0x70, 0x63,
	0x43, 0x57, 0x4d, 0x50, 0x62, 0x2e, 0x50, 0x75, 0x73, 0x68, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x49,
	0x6e, 0x66, 0x6f, 0x52, 0x0d, 0x70, 0x75, 0x73, 0x68, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x49, 0x6e,
	0x66, 0x6f, 0x42, 0x1c, 0x5a, 0x1a, 0x73, 0x6f, 0x6c, 0x2e, 0x67, 0x6f, 0x2f, 0x63, 0x77, 0x6d,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x43, 0x57, 0x4d, 0x50, 0x62,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_grpc_cwm_rq_res_account_proto_rawDescOnce sync.Once
	file_grpc_cwm_rq_res_account_proto_rawDescData = file_grpc_cwm_rq_res_account_proto_rawDesc
)

func file_grpc_cwm_rq_res_account_proto_rawDescGZIP() []byte {
	file_grpc_cwm_rq_res_account_proto_rawDescOnce.Do(func() {
		file_grpc_cwm_rq_res_account_proto_rawDescData = protoimpl.X.CompressGZIP(file_grpc_cwm_rq_res_account_proto_rawDescData)
	})
	return file_grpc_cwm_rq_res_account_proto_rawDescData
}

var file_grpc_cwm_rq_res_account_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_grpc_cwm_rq_res_account_proto_goTypes = []interface{}{
	(*CreatAccountRequest)(nil),         // 0: grpcCWMPb.CreatAccountRequest
	(*CreatAccountResponse)(nil),        // 1: grpcCWMPb.CreatAccountResponse
	(*VerifyAuthencodeRequest)(nil),     // 2: grpcCWMPb.VerifyAuthencodeRequest
	(*VerifyAuthencodeResponse)(nil),    // 3: grpcCWMPb.VerifyAuthencodeResponse
	(*LoginRequest)(nil),                // 4: grpcCWMPb.LoginRequest
	(*LoginResponse)(nil),               // 5: grpcCWMPb.LoginResponse
	(*SyncContactRequest)(nil),          // 6: grpcCWMPb.SyncContactRequest
	(*SyncContactResponse)(nil),         // 7: grpcCWMPb.SyncContactResponse
	(*UpdateProfileRequest)(nil),        // 8: grpcCWMPb.UpdateProfileRequest
	(*UpdateProfileResponse)(nil),       // 9: grpcCWMPb.UpdateProfileResponse
	(*UpdateUsernameRequest)(nil),       // 10: grpcCWMPb.UpdateUsernameRequest
	(*UpdateUsernameResponse)(nil),      // 11: grpcCWMPb.UpdateUsernameResponse
	(*SearchByUsernameRequest)(nil),     // 12: grpcCWMPb.SearchByUsernameRequest
	(*SearchByUsernameResponse)(nil),    // 13: grpcCWMPb.SearchByUsernameResponse
	(*SearchByPhoneFullRequest)(nil),    // 14: grpcCWMPb.SearchByPhoneFullRequest
	(*SearchByPhoneFullResponse)(nil),   // 15: grpcCWMPb.SearchByPhoneFullResponse
	(*FindByListPhoneFullRequest)(nil),  // 16: grpcCWMPb.FindByListPhoneFullRequest
	(*FindByListPhoneFullResponse)(nil), // 17: grpcCWMPb.FindByListPhoneFullResponse
	(*UpdatePushTokenRequest)(nil),      // 18: grpcCWMPb.UpdatePushTokenRequest
	(*UpdatePushTokenResponse)(nil),     // 19: grpcCWMPb.UpdatePushTokenResponse
	(*DeviceInfo)(nil),                  // 20: grpcCWMPb.DeviceInfo
	(*ContactInfo)(nil),                 // 21: grpcCWMPb.ContactInfo
	(*SearchUserInfo)(nil),              // 22: grpcCWMPb.SearchUserInfo
	(*PushTokenInfo)(nil),               // 23: grpcCWMPb.PushTokenInfo
}
var file_grpc_cwm_rq_res_account_proto_depIdxs = []int32{
	20, // 0: grpcCWMPb.VerifyAuthencodeRequest.deviceInfo:type_name -> grpcCWMPb.DeviceInfo
	20, // 1: grpcCWMPb.VerifyAuthencodeResponse.deviceInfo:type_name -> grpcCWMPb.DeviceInfo
	21, // 2: grpcCWMPb.SyncContactRequest.contactInfo:type_name -> grpcCWMPb.ContactInfo
	21, // 3: grpcCWMPb.SyncContactResponse.contactInfo:type_name -> grpcCWMPb.ContactInfo
	22, // 4: grpcCWMPb.SearchByUsernameResponse.searchUserInfos:type_name -> grpcCWMPb.SearchUserInfo
	22, // 5: grpcCWMPb.SearchByPhoneFullResponse.searchUserInfos:type_name -> grpcCWMPb.SearchUserInfo
	22, // 6: grpcCWMPb.FindByListPhoneFullResponse.searchUserInfos:type_name -> grpcCWMPb.SearchUserInfo
	23, // 7: grpcCWMPb.UpdatePushTokenRequest.pushTokenInfo:type_name -> grpcCWMPb.PushTokenInfo
	23, // 8: grpcCWMPb.UpdatePushTokenResponse.pushTokenInfo:type_name -> grpcCWMPb.PushTokenInfo
	9,  // [9:9] is the sub-list for method output_type
	9,  // [9:9] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_grpc_cwm_rq_res_account_proto_init() }
func file_grpc_cwm_rq_res_account_proto_init() {
	if File_grpc_cwm_rq_res_account_proto != nil {
		return
	}
	file_grpc_cwm_model_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_grpc_cwm_rq_res_account_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreatAccountRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_cwm_rq_res_account_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreatAccountResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_cwm_rq_res_account_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VerifyAuthencodeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_cwm_rq_res_account_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VerifyAuthencodeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_cwm_rq_res_account_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LoginRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_cwm_rq_res_account_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LoginResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_cwm_rq_res_account_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SyncContactRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_cwm_rq_res_account_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SyncContactResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_cwm_rq_res_account_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateProfileRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_cwm_rq_res_account_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateProfileResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_cwm_rq_res_account_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateUsernameRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_cwm_rq_res_account_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateUsernameResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_cwm_rq_res_account_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SearchByUsernameRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_cwm_rq_res_account_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SearchByUsernameResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_cwm_rq_res_account_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SearchByPhoneFullRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_cwm_rq_res_account_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SearchByPhoneFullResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_cwm_rq_res_account_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FindByListPhoneFullRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_cwm_rq_res_account_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FindByListPhoneFullResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_cwm_rq_res_account_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdatePushTokenRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_cwm_rq_res_account_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdatePushTokenResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_grpc_cwm_rq_res_account_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_grpc_cwm_rq_res_account_proto_goTypes,
		DependencyIndexes: file_grpc_cwm_rq_res_account_proto_depIdxs,
		MessageInfos:      file_grpc_cwm_rq_res_account_proto_msgTypes,
	}.Build()
	File_grpc_cwm_rq_res_account_proto = out.File
	file_grpc_cwm_rq_res_account_proto_rawDesc = nil
	file_grpc_cwm_rq_res_account_proto_goTypes = nil
	file_grpc_cwm_rq_res_account_proto_depIdxs = nil
}
